name: tekwise

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: tekwise
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm i --force

      - name: Build application
        run: CI=false npm run build